name: test_apptainer

on: [push]

jobs:
  apptainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        uses: omnibenchmark/run_omnibenchmark@${{ github.ref_name }}
        with:
          yaml: tests/Clustering_apptainer.yml
          backend: apptainer
          cores: 1

